-- ================================================================
-- SETUP NODO CBBA  |  PostgreSQL
-- ================================================================
-- Cada nodo fragmenta SOLO sus propios datos.
-- CBBA usa sus fragmentos como tablas de trabajo en la app.
--
-- Fragmentos que crea este script:
--   frag_paciente_cbba   : horizontal primaria (id_hospital = 2)
--   frag_doctor_cbba     : horizontal primaria (id_hospital = 2)
--   historial_clinico_v1 : vertical — columnas criticas
--   historial_clinico_v2 : vertical — columnas pesadas (solo CBBA)
--   frag_consulta_cbba   : horizontal derivada
--   frag_emergencia_cbba : horizontal derivada
--   frag_transferencia_cbba: horizontal derivada
--
-- Catalogos sin fragmentar (replica identica en los 3 nodos):
--   hospital, medicamento
--
-- Ejecutar:
--   psql -U postgres -c "CREATE DATABASE hospital_cbba;"
--   psql -U postgres -d hospital_cbba -f setup_cbba.sql
-- ================================================================

-- ================================================================
-- CATALOGOS NACIONALES  (replica identica en LPZ, CBBA y STCZ)
-- ================================================================

CREATE TABLE IF NOT EXISTS hospital (
    id_hospital  INT         PRIMARY KEY,
    nombre       VARCHAR(150) NOT NULL,
    ciudad       VARCHAR(80),
    direccion    VARCHAR(250),
    telefono     VARCHAR(20)
);

CREATE TABLE IF NOT EXISTS medicamento (
    id_medicamento INT         PRIMARY KEY,
    nombre         VARCHAR(120) NOT NULL,
    descripcion    TEXT,
    dosis          VARCHAR(80),
    fabricante     VARCHAR(120)
);

-- ================================================================
-- FRAGMENTO HORIZONTAL PRIMARIO: frag_paciente_cbba
-- Criterio: id_hospital = 2  |  IDs: 10000 – 19 999
-- GENERATED BY DEFAULT permite insertar IDs explicitos al recibir
-- transferencias de LPZ (1-9999) o STCZ (20000+).
-- ================================================================

CREATE TABLE IF NOT EXISTS frag_paciente_cbba (
    id_paciente      INT GENERATED BY DEFAULT AS IDENTITY (START 10000) PRIMARY KEY,
    nombre           VARCHAR(100) NOT NULL,
    apellido         VARCHAR(100) NOT NULL,
    ci               VARCHAR(20)  UNIQUE,
    fecha_nacimiento DATE,
    sexo             VARCHAR(15),
    direccion        VARCHAR(250),
    telefono         VARCHAR(20),
    tipo_sangre      VARCHAR(5),
    alergias         TEXT DEFAULT '',
    id_hospital      INT  DEFAULT 2
);

-- ================================================================
-- FRAGMENTO HORIZONTAL PRIMARIO: frag_doctor_cbba
-- Criterio: id_hospital = 2
-- ================================================================

CREATE TABLE IF NOT EXISTS frag_doctor_cbba (
    id_doctor    INT GENERATED BY DEFAULT AS IDENTITY (START 10000) PRIMARY KEY,
    nombre       VARCHAR(100) NOT NULL,
    apellido     VARCHAR(100) NOT NULL,
    especialidad VARCHAR(120),
    telefono     VARCHAR(20),
    correo       VARCHAR(120),
    id_hospital  INT DEFAULT 2
);

-- ================================================================
-- FRAGMENTACION VERTICAL: historial_clinico  →  V1 + V2
-- ================================================================

CREATE TABLE IF NOT EXISTS historial_clinico_v1 (
    id_historial          INT GENERATED BY DEFAULT AS IDENTITY (START 10000) PRIMARY KEY,
    id_paciente           INT UNIQUE,
    tipo_sangre           VARCHAR(5),
    alergias              TEXT DEFAULT '',
    enfermedades_cronicas TEXT DEFAULT ''
);

CREATE TABLE IF NOT EXISTS historial_clinico_v2 (
    id_historial  INT PRIMARY KEY,
    id_paciente   INT,
    fecha_apertura DATE DEFAULT CURRENT_DATE,
    antecedentes  TEXT DEFAULT '',
    observaciones TEXT DEFAULT ''
);

-- ================================================================
-- FRAGMENTOS HORIZONTALES DERIVADOS
-- ================================================================

CREATE TABLE IF NOT EXISTS frag_consulta_cbba (
    id_consulta INT GENERATED BY DEFAULT AS IDENTITY (START 10000) PRIMARY KEY,
    fecha       DATE DEFAULT CURRENT_DATE,
    hora        TIME DEFAULT CURRENT_TIME,
    motivo      TEXT,
    diagnostico TEXT,
    id_paciente INT,
    id_doctor   INT,
    id_hospital INT  DEFAULT 2
);

CREATE TABLE IF NOT EXISTS frag_emergencia_cbba (
    id_emergencia   INT GENERATED BY DEFAULT AS IDENTITY (START 10000) PRIMARY KEY,
    fecha           DATE DEFAULT CURRENT_DATE,
    hora            TIME DEFAULT CURRENT_TIME,
    tipo_emergencia VARCHAR(120),
    estado_paciente VARCHAR(120),
    observaciones   TEXT,
    id_paciente     INT,
    id_hospital     INT  DEFAULT 2
);

CREATE TABLE IF NOT EXISTS frag_transferencia_cbba (
    id_transferencia    INT GENERATED BY DEFAULT AS IDENTITY (START 10000) PRIMARY KEY,
    fecha_transferencia DATE        DEFAULT CURRENT_DATE,
    motivo              TEXT,
    estado              VARCHAR(50) DEFAULT 'Pendiente',
    id_paciente         INT,
    id_hospital_origen  INT         DEFAULT 2,
    id_hospital_destino INT
);

CREATE TABLE IF NOT EXISTS receta (
    id_receta    INT GENERATED BY DEFAULT AS IDENTITY (START 10000) PRIMARY KEY,
    fecha        DATE DEFAULT CURRENT_DATE,
    indicaciones TEXT,
    id_consulta  INT
);

CREATE TABLE IF NOT EXISTS receta_medicamento (
    id_receta      INT,
    id_medicamento INT,
    cantidad       INT DEFAULT 1,
    PRIMARY KEY (id_receta, id_medicamento)
);

CREATE TABLE IF NOT EXISTS historial_replica (
    id_replica            SERIAL PRIMARY KEY,
    id_paciente           INT         NOT NULL,
    hospital_origen       VARCHAR(10) NOT NULL,
    tipo_sangre           VARCHAR(5),
    alergias              TEXT DEFAULT '',
    enfermedades_cronicas TEXT DEFAULT '',
    fecha_actualizacion   TIMESTAMP DEFAULT NOW(),
    UNIQUE(id_paciente, hospital_origen)
);

-- ================================================================
-- DATOS INICIALES — CATALOGO NACIONAL (igual en los 3 nodos)
-- ================================================================

INSERT INTO hospital VALUES(1,'Hospital Central de La Paz','La Paz','Av. Saavedra 2000, Miraflores','+591-2-2224444') ON CONFLICT DO NOTHING;
INSERT INTO hospital VALUES(2,'Hospital Regional de Cochabamba','Cochabamba','Av. Aniceto Arce 456, Centro','+591-4-4221122') ON CONFLICT DO NOTHING;
INSERT INTO hospital VALUES(3,'Hospital del Oriente','Santa Cruz','Av. Cañoto 789, Equipetrol','+591-3-3334455') ON CONFLICT DO NOTHING;

INSERT INTO medicamento VALUES(1,'Paracetamol','Analgésico y antipirético','500mg cada 8h','Bagó Bolivia') ON CONFLICT DO NOTHING;
INSERT INTO medicamento VALUES(2,'Ibuprofeno','Antiinflamatorio no esteroideo','400mg cada 8h','Roemmers') ON CONFLICT DO NOTHING;
INSERT INTO medicamento VALUES(3,'Amoxicilina','Antibiótico de amplio espectro','500mg cada 8h x7d','INTI') ON CONFLICT DO NOTHING;
INSERT INTO medicamento VALUES(4,'Metformina','Antidiabético oral','850mg con comidas','Bagó Bolivia') ON CONFLICT DO NOTHING;
INSERT INTO medicamento VALUES(5,'Enalapril','Antihipertensivo IECA','10mg una vez al día','Roemmers') ON CONFLICT DO NOTHING;
INSERT INTO medicamento VALUES(6,'Omeprazol','Inhibidor bomba de protones','20mg antes desayuno','INTI') ON CONFLICT DO NOTHING;
INSERT INTO medicamento VALUES(7,'Aspirina','Antiagregante plaquetario','100mg una vez al día','Bayer') ON CONFLICT DO NOTHING;
INSERT INTO medicamento VALUES(8,'Loratadina','Antihistamínico','10mg una vez al día','Bagó Bolivia') ON CONFLICT DO NOTHING;
INSERT INTO medicamento VALUES(9,'Captopril','Antihipertensivo de rescate','25mg sublingual','Roemmers') ON CONFLICT DO NOTHING;
INSERT INTO medicamento VALUES(10,'Diclofenaco','Antiinflamatorio dolor agudo','75mg cada 12h','Bagó Bolivia') ON CONFLICT DO NOTHING;

-- ================================================================
-- DATOS INICIALES — FRAGMENTO CBBA  (solo id_hospital = 2)
-- ================================================================

-- Doctores CBBA
INSERT INTO frag_doctor_cbba(id_doctor,nombre,apellido,especialidad,telefono,correo,id_hospital) VALUES(10001,'Laura','Vásquez Rojas','Medicina General','60011111','lvasquez@hrcbba.bo',2) ON CONFLICT DO NOTHING;
INSERT INTO frag_doctor_cbba(id_doctor,nombre,apellido,especialidad,telefono,correo,id_hospital) VALUES(10002,'Miguel','Torrico Paz','Traumatología','60022222','mtorrico@hrcbba.bo',2) ON CONFLICT DO NOTHING;
INSERT INTO frag_doctor_cbba(id_doctor,nombre,apellido,especialidad,telefono,correo,id_hospital) VALUES(10003,'Sandra','Lima Arce','Ginecología','60033333','slima@hrcbba.bo',2) ON CONFLICT DO NOTHING;
SELECT setval(pg_get_serial_sequence('frag_doctor_cbba','id_doctor'), 10003);

-- Pacientes CBBA
INSERT INTO frag_paciente_cbba(id_paciente,nombre,apellido,ci,fecha_nacimiento,sexo,direccion,telefono,tipo_sangre,alergias,id_hospital) VALUES(10001,'Carlos','Mamani Quispe','4567890','1982-05-10','M','Av. Heroinas 234, Cbba','61111111','B+','Polen',2) ON CONFLICT DO NOTHING;
INSERT INTO frag_paciente_cbba(id_paciente,nombre,apellido,ci,fecha_nacimiento,sexo,direccion,telefono,tipo_sangre,alergias,id_hospital) VALUES(10002,'Ana','Lima Torres','5678901','1995-09-18','F','Calle Ecuador 567, Cbba','62222222','AB-','Ninguna',2) ON CONFLICT DO NOTHING;
INSERT INTO frag_paciente_cbba(id_paciente,nombre,apellido,ci,fecha_nacimiento,sexo,direccion,telefono,tipo_sangre,alergias,id_hospital) VALUES(10003,'Roberto','Herrera Vidal','5901234','1988-02-14','M','Av. Blanco Galindo 890, Cbba','63333333','O+','Aspirina',2) ON CONFLICT DO NOTHING;
SELECT setval(pg_get_serial_sequence('frag_paciente_cbba','id_paciente'), 10003);

-- Historial V1 — fragmento vertical critico (pacientes CBBA)
INSERT INTO historial_clinico_v1(id_historial,id_paciente,tipo_sangre,alergias,enfermedades_cronicas) VALUES(10001,10001,'B+','Polen','Asma leve') ON CONFLICT DO NOTHING;
INSERT INTO historial_clinico_v1(id_historial,id_paciente,tipo_sangre,alergias,enfermedades_cronicas) VALUES(10002,10002,'AB-','Ninguna','') ON CONFLICT DO NOTHING;
INSERT INTO historial_clinico_v1(id_historial,id_paciente,tipo_sangre,alergias,enfermedades_cronicas) VALUES(10003,10003,'O+','Aspirina','Diabetes tipo 2') ON CONFLICT DO NOTHING;
SELECT setval(pg_get_serial_sequence('historial_clinico_v1','id_historial'), 10003);

-- Historial V2 — fragmento vertical notas pesadas (quedan SOLO en CBBA)
INSERT INTO historial_clinico_v2(id_historial,id_paciente,fecha_apertura,antecedentes,observaciones) VALUES(10001,10001,'2026-01-20','Asma desde los 10 años.','Usar broncodilatador ante crisis.') ON CONFLICT DO NOTHING;
INSERT INTO historial_clinico_v2(id_historial,id_paciente,fecha_apertura,antecedentes,observaciones) VALUES(10002,10002,'2026-02-05','Sin antecedentes relevantes.','Paciente CBBA registrado.') ON CONFLICT DO NOTHING;
INSERT INTO historial_clinico_v2(id_historial,id_paciente,fecha_apertura,antecedentes,observaciones) VALUES(10003,10003,'2025-11-10','Diabetes desde 2015.','Control glucémico cada 3 meses.') ON CONFLICT DO NOTHING;

-- Consultas CBBA
INSERT INTO frag_consulta_cbba(id_consulta,fecha,hora,motivo,diagnostico,id_paciente,id_doctor,id_hospital) VALUES(10001,'2026-05-08','11:15','Dolor en rodilla derecha','Artritis leve.',10001,10001,2) ON CONFLICT DO NOTHING;
INSERT INTO frag_consulta_cbba(id_consulta,fecha,hora,motivo,diagnostico,id_paciente,id_doctor,id_hospital) VALUES(10002,'2026-05-09','14:00','Fractura brazo izquierdo','Fractura radio distal.',10002,10002,2) ON CONFLICT DO NOTHING;
SELECT setval(pg_get_serial_sequence('frag_consulta_cbba','id_consulta'), 10002);

-- Emergencias CBBA
INSERT INTO frag_emergencia_cbba(id_emergencia,fecha,hora,tipo_emergencia,estado_paciente,observaciones,id_paciente,id_hospital) VALUES(10001,'2026-05-14','03:20','Crisis hipertensiva','Estable','PA 190/110. Captopril.',10003,2) ON CONFLICT DO NOTHING;
SELECT setval(pg_get_serial_sequence('frag_emergencia_cbba','id_emergencia'), 10001);

-- ================================================================
-- RECONSTRUCCION NACIONAL  (referencia — se ejecuta en LPZ)
-- ================================================================
/*
  SELECT id_paciente, nombre, apellido, ci, tipo_sangre, alergias, 'LPZ' AS nodo
  FROM frag_paciente_lpz
UNION ALL
  SELECT id_paciente, nombre, apellido, ci, tipo_sangre, alergias, 'CBBA' AS nodo
  FROM frag_paciente_cbba                    -- esta tabla
UNION ALL
  SELECT id_paciente, nombre, apellido, ci, tipo_sangre, alergias, 'STCZ' AS nodo
  FROM frag_paciente_stcz
*/

-- ================================================================
-- VERIFICACION
-- ================================================================
SELECT 'frag_paciente_cbba'   AS fragmento, COUNT(*) AS n FROM frag_paciente_cbba
UNION ALL SELECT 'frag_doctor_cbba',         COUNT(*) FROM frag_doctor_cbba
UNION ALL SELECT 'historial_clinico_v1',     COUNT(*) FROM historial_clinico_v1
UNION ALL SELECT 'historial_clinico_v2',     COUNT(*) FROM historial_clinico_v2
UNION ALL SELECT 'frag_consulta_cbba',       COUNT(*) FROM frag_consulta_cbba
UNION ALL SELECT 'frag_emergencia_cbba',     COUNT(*) FROM frag_emergencia_cbba
UNION ALL SELECT 'hospital (catalogo)',       COUNT(*) FROM hospital
UNION ALL SELECT 'medicamento (catalogo)',    COUNT(*) FROM medicamento;
